{% set name = "scanpy" %}
{% set version = "1.3.3_cb8aca9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}
build:
  number: 0
  skip: True # [not py36]
source:
  url: https://github.com/grst/scanpy/archive/cb8aca90045549a991c1d23b58c64e8ebb296350.tar.gz
  sha256: 764d2e5c473ca2d1f1e628c8730f27309ee3a5b12eb822c29079b2c88943831f

requirements:
  host:
    - python
    - setuptools

  run:
    - python
    - setuptools
    - seaborn
    - scikit-learn
    - statsmodels
    - numba
    - python-igraph
    - louvain
    - 'anndata >=0.6.10'
    - 'matplotlib >=2.2'
    - 'pandas >=0.21'
    - scipy
    - h5py
    - pytables
    - networkx
    - natsort

test:
  imports:
    - scanpy

about:
  home: https://scanpy.readthedocs.io/en/latest/
  license: BSD-3
  summary: Single-Cell Analysis in Python. Scales to >1M cells.

extra:
  identifiers:
    - doi:10.1186/s13059-017-1382-0
