{% set name = "scanpy" %}
{% set version = "1.3.3_b0df581" %}

package:
  name: {{ name|lower }}
  version: {{ version }}
build:
  number: 0
  skip: True # [not py36]
source:
  url: https://github.com/grst/scanpy/archive/b0df581ac433f03317c4e55d06cd269d1fc43ea7.tar.gz
  sha256: 20bbc33be974e72c7557a06ba49e38d15d220e488fa7e44285156834310bcf61

requirements:
  host:
    - python
    - setuptools

  run:
    - python
    - setuptools
    - seaborn
    - scikit-learn
    - statsmodels
    - numba
    - python-igraph
    - louvain
    - 'anndata >=0.6.10'
    - 'matplotlib >=2.2'
    - 'pandas >=0.21'
    - scipy
    - h5py
    - pytables
    - networkx
    - natsort

test:
  imports:
    - scanpy

about:
  home: https://scanpy.readthedocs.io/en/latest/
  license: BSD-3
  summary: Single-Cell Analysis in Python. Scales to >1M cells.

extra:
  identifiers:
    - doi:10.1186/s13059-017-1382-0
