{% set name = "doubletdetection" %}
{% set version = "2.4" %}
{% set sha256 = "34ac61e0eec10cd872f59e106cf09c82ec8acdf43268a20421e1626ac92aac97" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/JonathanShor/DoubletDetection/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - pip
    - python

  run:
    - multicore-tsne =0.1_d4ff4aab
    - matplotlib >=3.0.0
    - numpy >=1.13
    - pandas >=0.23
    - scipy >=1.1.0
    - scikit-learn >=0.20
    - pytables >=3.4
    - phenograph =1.5.2_15a4f8ac

test:
  imports:
    - doubletdetection

about:
  home: http://github.com/theislab/scanp://github.com/JonathanShor/DoubletDetection
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Doublet detection in single-cell RNA-seq data.

extra:
  recipe-maintainers:
    - grst
